# BEGIN FOR POSTFIXADMIN

# File location(Debian):
#   /etc/postfixadmin/apache.conf
#   -> link to /etc/apache2/conf-available/postfixadmin.conf

<Directory "/usr/share/postfixadmin/public">
    Options FollowSymLinks
    AllowOverride None
    # 必须在这里也授予基础访问权限
    Require all granted
</Directory>

Alias /postfixadmin /usr/share/postfixadmin/public
<Location "/postfixadmin">
    <RequireAny>
        Require ip 127.0.0.1
        Require ip ::1
        #Require ip 10.10.0.0/24
    </RequireAny>
</Location>

# END FOR POSTFIXADMIN
